#!/usr/bin/env bash

echo "Creating database excobox.github.io..."
pgmgr db create

echo "Running migrations..."
pgmgr db migrate

echo "Creating database excobox.github.io-test"
pgmgr -c ".pgmgr.test.json" db create

echo "Running migration on postgres://aididrizovic@localhost:5432/excobox.github.io-test?sslmode=disable..."
pgmgr -c ".pgmgr.test.json" db migrate
